#!/bin/bash
#           - Do this go get proper highlighting for the editor I use.

# hw3prb3 -- Write an interactive script called adduser...
# Andrew Robinson
# Add a user to the system, with a script.
