#!/bin/bash
#           - Do this go get proper highlighting for the editor I use.

# hw3prb3 -- Write a shell script called watchdog...
# Andrew Robinson
# Watch for usernames that log on, that are listed in .friends file.
